### ISSUE TITLE
unrecognized option '--vimgrep'

### ISSUE THREAD

**Issue by jchlanda** [rking/ag.vim#83] opened 2015-01-16 11:36 UTC
Hi,

It would appear that the commit: 3286d6c6d0 introduced a bug. Every use of ag now gives: 
```
ag: unrecognized option '--vimgrep'

Usage: ag [FILE-TYPE] [OPTIONS] PATTERN [PATH]
```

I'm using:
`ag version 0.22.0`

Thanks.

**Comment by losingkeys** [comment] 2015-01-16 12:38
Duplicate of #82.

**Closed by losingkeys** 2015-01-16 12:38 UTC
